name: Build Minimal pyodbc Layer

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Build Simple Layer
        run: |
          # Create layer structure
          mkdir -p layer/python/lib/python3.9/site-packages
          
          # Install pyodbc
          pip install pyodbc -t layer/python/lib/python3.9/site-packages
          
          # Create placeholder for ODBC config
          mkdir -p layer/opt
          echo '[ODBC Driver 17 for SQL Server]' > layer/opt/odbcinst.ini
          echo 'Description=Microsoft ODBC Driver 17 for SQL Server' >> layer/opt/odbcinst.ini
          echo 'Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.4.1' >> layer/opt/odbcinst.ini
          
          # Create zip
          cd layer
          zip -r ../pyodbc-layer.zip .
          cd ..
          
          # Show file info
          ls -la pyodbc-layer.zip
          
          # Create public link using transfer.sh
          echo "Creating download link..."
          DOWNLOAD_URL=$(curl --upload-file pyodbc-layer.zip https://transfer.sh/pyodbc-layer.zip)
          echo "Download your layer using this link (valid for 14 days):"
          echo "$DOWNLOAD_URL"
          
          # Also provide alternative using file.io (7 day link)
          ALT_URL=$(curl -F "file=@pyodbc-layer.zip" https://file.io)
          echo "Alternative download link:"
          echo "$ALT_URL"
