name: Build pyodbc Layer with Linux Drivers

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Microsoft ODBC Drivers
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
      
      - name: Build Layer
        run: |
          mkdir -p python/lib/python3.13/site-packages
          mkdir -p opt/python/lib/python3.13/site-packages
          mkdir -p opt/microsoft/msodbcsql17
          
          # Install pyodbc to both paths
          pip install pyodbc -t python/lib/python3.13/site-packages
          pip install pyodbc -t opt/python/lib/python3.13/site-packages
          
          # Copy ODBC drivers
          sudo cp -r /opt/microsoft/msodbcsql17 opt/microsoft/
          sudo cp /etc/odbcinst.ini opt/
          sudo chown -R $USER:$USER opt
          
          # Verify structure
          find . -type d | sort
          
          # Create zip
          zip -r pyodbc-layer.zip python opt
      
      - name: Upload Layer Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pyodbc-layer-python3.13
          path: pyodbc-layer.zip
