name: Build pyodbc Layer with Artifacts

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Build Layer
        run: |
          # Create layer structure
          mkdir -p layer/python/lib/python3.9/site-packages
          
          # Install pyodbc
          pip install pyodbc -t layer/python/lib/python3.9/site-packages
          
          # Create config for ODBC
          mkdir -p layer/opt
          echo '[ODBC Driver 17 for SQL Server]' > layer/opt/odbcinst.ini
          echo 'Description=Microsoft ODBC Driver 17 for SQL Server' >> layer/opt/odbcinst.ini
          echo 'Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.4.1' >> layer/opt/odbcinst.ini
          
          # Create zip
          cd layer
          zip -r ../pyodbc-layer.zip .
          cd ..
          
          # Show file info
          ls -la pyodbc-layer.zip
          echo "Layer size: $(du -h pyodbc-layer.zip | cut -f1)"
      
      - name: Upload Layer ZIP
        uses: actions/upload-artifact@v4
        with:
          name: pyodbc-layer
          path: pyodbc-layer.zip
