name: Build Complete pyodbc Layer with Drivers

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Microsoft ODBC Drivers
        run: |
          # Add Microsoft repositories
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          
          # Update packages
          sudo apt-get update
          
          # Install ODBC driver and tools
          echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
          
          # Check driver installation
          echo "Checking ODBC drivers:"
          odbcinst -j
          cat /etc/odbcinst.ini
      
      - name: Build Layer with Drivers
        run: |
          # Create layer structure
          mkdir -p layer/python/lib/python3.9/site-packages
          mkdir -p layer/opt
          
          # Install pyodbc
          pip install pyodbc -t layer/python/lib/python3.9/site-packages
          
          # Copy Microsoft ODBC drivers to layer
          sudo mkdir -p layer/opt/microsoft
          sudo cp -r /opt/microsoft/msodbcsql17 layer/opt/microsoft/
          sudo chown -R $USER:$USER layer/opt
          
          # Copy ODBC configuration files
          cp /etc/odbcinst.ini layer/opt/
          
          # List all files in the layer to verify
          echo "Verifying layer contents:"
          find layer -type f | sort
          
          # Create zip
          cd layer
          zip -r ../pyodbc-layer.zip .
          cd ..
          
          # Show file info
          ls -la pyodbc-layer.zip
          echo "Layer size: $(du -h pyodbc-layer.zip | cut -f1)"
      
      - name: Upload Layer ZIP
        uses: actions/upload-artifact@v4
        with:
          name: pyodbc-layer-with-drivers
          path: pyodbc-layer.zip
