name: Build pyodbc Layer for Python 3.13

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # GitHub Actions doesn't yet have 3.13
      
      - name: Install Microsoft ODBC Drivers
        run: |
          # Add Microsoft repositories
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
      
      - name: Build Layer
        run: |
          # Use 3.13 for directory structure (even though we're using 3.11 to build)
          mkdir -p python/lib/python3.13/site-packages
          pip install pyodbc -t python/lib/python3.13/site-packages
          
          # Copy Microsoft ODBC drivers
          mkdir -p opt/microsoft
          sudo cp -r /opt/microsoft/msodbcsql17 opt/microsoft/
          sudo cp /etc/odbcinst.ini opt/
          sudo chown -R $USER:$USER opt
          
          # Verify directory structure
          echo "Layer structure:"
          find . -type d | sort
          
          # Create zip WITHOUT a top-level directory
          zip -r pyodbc-layer.zip python opt
          
          # Show file info
          ls -la pyodbc-layer.zip
          echo "Layer size: $(du -h pyodbc-layer.zip | cut -f1)"
      
      - name: Upload Layer ZIP
        uses: actions/upload-artifact@v4
        with:
          name: pyodbc-layer-python3.13
          path: pyodbc-layer.zip
